import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@mui/material/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>One mintue create a Dapp</h1>

        <Link href="/create">
          <Button variant="contained" size="large">
            Get Start 🚀
          </Button>
        </Link>
      </main>
    </>
  );
}
